name: jellyflix
description: "Another Jellyfin client for Android, iOS, Windows, macOS, Linux and Web."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' 

version: 99.99.99+99

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  openapi:
    git: https://github.com/jdk-21/jellyfin-api-dart.git
  media_kit: ^1.1.10                             # Primary package.
  media_kit_video: ^1.2.4                        # For video rendering.
  media_kit_libs_video: ^1.0.4                   # For video rendering.
  path_provider: ^2.1.1
  universal_platform: ^1.0.0+1
  url_launcher: ^6.2.1
  hooks_riverpod: ^2.4.9
  flutter_hooks: ^0.20.3
  riverpod_annotation: ^2.3.3
  flutter_secure_storage: ^9.0.0
  permission_handler: ^11.1.0
  filter_list: ^1.0.2
  built_collection: ^5.1.1
  dots_indicator: ^3.0.0
  go_router: ^13.0.0
  skeletonizer: ^0.8.0
  cached_network_image: ^3.3.1
  flutter_blurhash: ^0.8.2
  flutter_downloader: ^1.11.6
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#000000"
    theme_color: "#673AB7"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/macOS_icon.png"
